name: Trivy (Docker and IaC)

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/Dockerfile*"
      - "**/*.tf"
      - "**/*.tfvars"
      - "**/*.bicep"
      - "**/k8s/**/*.y*ml"
      - "**/helm/**/*.y*ml"
  push:
    branches:
      - main
    paths:
      - "**/Dockerfile*"
      - "**/*.tf"
      - "**/*.tfvars"
      - "**/*.bicep"
      - "**/k8s/**/*.y*ml"
      - "**/helm/**/*.y*ml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8 # v0.24.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-results.sarif
          scanners: vuln,misconfig,secret
          severity: CRITICAL,HIGH

      - name: Upload Trivy SARIF artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: trivy-sarif
          path: trivy-results.sarif
          if-no-files-found: error

  trivy-code-scanning-upload:
    needs: trivy-scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Download Trivy SARIF artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: trivy-sarif

      - name: Upload Trivy SARIF to GitHub code scanning
        uses: github/codeql-action/upload-sarif@ce64ddcb0d8d890d2df4a9d1c04ff297367dea2a # v3
        with:
          sarif_file: trivy-results.sarif
