name: Trivy (Docker and IaC)

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/Dockerfile*"
      - "**/*.tf"
      - "**/*.tfvars"
      - "**/*.bicep"
      - "**/k8s/**/*.y*ml"
      - "**/helm/**/*.y*ml"
  push:
    branches:
      - main
    paths:
      - "**/Dockerfile*"
      - "**/*.tf"
      - "**/*.tfvars"
      - "**/*.bicep"
      - "**/k8s/**/*.y*ml"
      - "**/helm/**/*.y*ml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-results.sarif
          scanners: vuln,misconfig,secret
          severity: CRITICAL,HIGH

      - name: Upload Trivy SARIF artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: trivy-sarif
          path: trivy-results.sarif
          if-no-files-found: error

  trivy-code-scanning-upload:
    needs: trivy-scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Download Trivy SARIF artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: trivy-sarif

      - name: Upload Trivy SARIF to GitHub code scanning
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4
        with:
          sarif_file: trivy-results.sarif
